export const RESET_STORE = 'RESET_STORE';
export const RESET_CAPTCHA = 'RESET_CAPTCHA';

/* AUTH */
export const LOGIN_USER = 'LOGIN_USER';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';
export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGOUT_USER = 'LOGOUT_USER';
export const FORGET_PASSWORD = 'FORGET_PASSWORD';
export const FORGET_PASSWORD_SUCCESS = 'FORGET_PASSWORD_SUCCESS';
export const FORGET_PASSWORD_FAILED = 'FORGET_PASSWORD_FAILED';
export const ON_DISMISS = 'ON_DISMISS';

/* PROFILE */
export const GET_USER_PROFILE = 'GET_USER_PROFILE';
export const GET_USER_PROFILE_SUCCESS = 'GET_USER_PROFILE_SUCCESS';
export const GET_USER_PROFILE_FAILED = 'GET_USER_PROFILE_FAILED';

/* COMMON */
export const ON_CHANGE_PATH_INFO = 'ON_CHANGE_PATH_INFO';
export const ON_CHANGE_ROW = 'ON_CHANGE_ROW';
export const ON_CHANGE_PAGE = 'ON_CHANGE_PAGE';
export const ON_CHANGE_SEARCH = 'ON_CHANGE_SEARCH';
export const ON_CHANGE_DATE = 'ON_CHANGE_DATE';
export const ON_CHANGE_CATEGORY = 'ON_CHANGE_CATEGORY';
export const ON_CHANGE_SORT = 'ON_CHANGE_SORT';

/* PROFIL */
export const UPDATE_PROFILE_ACCOUNT = 'UPDATE_PROFILE_ACCOUNT';
export const UPDATE_PROFILE_ACCOUNT_SUCCESS = 'UPDATE_PROFILE_ACCOUNT_SUCCESS';
export const UPDATE_PROFILE_ACCOUNT_FAILED = 'UPDATE_PROFILE_ACCOUNT_FAILED';

export const UPDATE_PROFILE_MARKET = 'UPDATE_PROFILE_MARKET';
export const UPDATE_PROFILE_MARKET_SUCCESS = 'UPDATE_PROFILE_MARKET_SUCCESS';
export const UPDATE_PROFILE_MARKET_FAILED = 'UPDATE_PROFILE_MARKET_FAILED';

export const UPDATE_PASSWORD = 'UPDATE_PASSWORD';
export const UPDATE_PASSWORD_SUCCESS = 'UPDATE_PASSWORD_SUCCESS';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';

/* PRODUCT */
export const GET_PRODUCT = 'GET_PRODUCT';
export const GET_PRODUCT_SUCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILED = 'GET_PRODUCT_FAILED';

export const GET_PRODUCT_CATEGORY = 'GET_PRODUCT_CATEGORY';
export const GET_PRODUCT_CATEGORY_SUCCESS = 'GET_PRODUCT_CATEGORY_SUCCESS';
export const GET_PRODUCT_CATEGORY_FAILED = 'GET_PRODUCT_CATEGORY_FAILED';

export const GET_PRODUCT_ALL_CATEGORIES = 'GET_PRODUCT_ALL_CATEGORIES';
export const GET_PRODUCT_ALL_CATEGORIES_SUCCESS =
	'GET_PRODUCT_ALL_CATEGORIES_SUCCESS';
export const GET_PRODUCT_ALL_CATEGORIES_FAILED =
	'GET_PRODUCT_ALL_CATEGORIES_FAILED';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS';
export const ADD_PRODUCT_FAILED = 'ADD_PRODUCT_FAILED';

export const GET_PRODUCT_DETAIL = 'GET_PRODUCT_DETAIL';
export const GET_PRODUCT_DETAIL_SUCCESS = 'GET_PRODUCT_DETAIL_SUCCESS';
export const GET_PRODUCT_DETAIL_FAILED = 'GET_PRODUCT_DETAIL_FAILED';

export const UPDATE_PRODUCT_DETAIL = 'UPDATE_PRODUCT_DETAIL';
export const UPDATE_PRODUCT_DETAIL_SUCCESS = 'UPDATE_PRODUCT_DETAIL_SUCCESS';
export const UPDATE_PRODUCT_DETAIL_FAILED = 'UPDATE_PRODUCT_DETAIL_FAILED';

export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS';
export const DELETE_PRODUCT_FAILED = 'DELETE_PRODUCT_FAILED';

/* ORDER */
export const GET_ALL_NEW_ORDER = 'GET_ALL_NEW_ORDER';
export const GET_ALL_NEW_ORDER_SUCCESS = 'GET_ALL_NEW_ORDER_SUCCESS';
export const GET_ALL_NEW_ORDER_FAILED = 'GET_ALL_NEW_ORDER_FAILED';

export const GET_ALL_ORDER_RECEIVED_SUCCESS = 'GET_ALL_ORDER_RECEIVED_SUCCESS';
export const GET_ALL_ORDER_IN_SHIPPING_SUCCESS =
	'GET_ALL_ORDER_IN_SHIPPING_SUCCESS';

export const GET_DETAIL_ORDER = 'GET_DETAIL_ORDER';
export const GET_DETAIL_ORDER_SUCCESS = 'GET_DETAIL_ORDER_SUCCESS';
export const GET_DETAIL_ORDER_FAILED = 'GET_DETAIL_ORDER_FAILED';

export const UPDATE_ORDER_STATUS = 'UPDATE_ORDER_STATUS';
export const UPDATE_ORDER_STATUS_SUCCESS = 'UPDATE_ORDER_STATUS_SUCCESS';
export const UPDATE_ORDER_STATUS_FAILED = 'UPDATE_ORDER_STATUS_FAILED';

export const GET_SHIPPING_STATUS = 'GET_SHIPPING_STATUS';
export const GET_SHIPPING_STATUS_SUCCESS = 'GET_SHIPPING_STATUS_SUCCESS';
export const GET_SHIPPING_STATUS_FAILED = 'GET_SHIPPING_STATUS_FAILED';

/* WITHDRAW */
export const GET_WITHDRAW_HISTORY = 'GET_WITHDRAW_HISTORY';
export const GET_WITHDRAW_HISTORY_SUCCESS = 'GET_WITHDRAW_HISTORY_SUCCESS';
export const GET_WITHDRAW_HISTORY_FAILED = 'GET_WITHDRAW_HISTORY_FAILED';

export const GET_INCOME_HISTORY = 'GET_INCOME_HISTORY';
export const GET_INCOME_HISTORY_SUCCESS = 'GET_INCOME_HISTORY_SUCCESS';
export const GET_INCOME_HISTORY_FAILED = 'GET_INCOME_HISTORY_FAILED';

/* SUBMISSION SELLER MANAGEMENT (ADMIN) */
export const GET_ALL_SUBMISSION = 'GET_ALL_SUBMISSION';
export const GET_ALL_SUBMISSION_SUCCESS = 'GET_ALL_SUBMISSION_SUCCESS';
export const GET_ALL_SUBMISSION_FAILED = 'GET_ALL_SUBMISSION_FAILED';

export const UPDATE_APPROVED_SUBMISSION = 'UPDATE_APPROVED_SUBMISSION';
export const UPDATE_APPROVED_SUBMISSION_SUCCESS =
	'UPDATE_APPROVED_SUBMISSION_SUCCESS';
export const UPDATE_APPROVED_SUBMISSION_FAILED =
	'UPDATE_APPROVED_SUBMISSION_FAILED';

export const UPDATE_UNAPPROVED_SUBMISSION = 'UPDATE_UNAPPROVED_SUBMISSION';
export const UPDATE_UNAPPROVED_SUBMISSION_SUCCESS =
	'UPDATE_UNAPPROVED_SUBMISSION_SUCCESS';
export const UPDATE_UNAPPROVED_SUBMISSION_FAILED =
	'UPDATE_UNAPPROVED_SUBMISSION_FAILED';

/* USER MANAGEMENT (ADMIN) */
export const GET_ALL_USER = 'GET_ALL_USER';
export const GET_ALL_USER_SUCCESS = 'GET_ALL_USER_SUCCESS';
export const GET_ALL_USER_FAILED = 'GET_ALL_USER_FAILED';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILED = 'GET_USER_FAILED';

/* ARTICLE MANAGEMENT */
export const GET_ALL_ARTICLE = 'GET_ALL_ARTICLE';
export const GET_ALL_ARTICLE_SUCCESS = 'GET_ALL_ARTICLE_SUCCESS';
export const GET_ALL_ARTICLE_FAILED = 'GET_ALL_ARTICLE_FAILED';

export const GET_DETAIL_ARTICLE = 'GET_DETAIL_ARTICLE';
export const GET_DETAIL_ARTICLE_SUCCESS = 'GET_DETAIL_ARTICLE_SUCCESS';
export const GET_DETAIL_ARTICLE_FAILED = 'GET_DETAIL_ARTICLE_FAILED';

export const UPDATE_DETAIL_ARTICLE = 'UPDATE_DETAIL_ARTICLE';
export const UPDATE_DETAIL_ARTICLE_SUCCESS = 'UPDATE_DETAIL_ARTICLE_SUCCESS';
export const UPDATE_DETAIL_ARTICLE_FAILED = 'UPDATE_DETAIL_ARTICLE_FAILED';

/* MARKET MANAGEMENT (ADMIN) */
export const GET_ALL_MARKET = 'GET_ALL_MARKET';
export const GET_ALL_MARKET_SUCCESS = 'GET_ALL_MARKET_SUCCESS';
export const GET_ALL_MARKET_FAILED = 'GET_ALL_MARKET_FAILED';

export const GET_MARKET_DETAIL = 'GET_MARKET_DETAIL';
export const GET_MARKET_DETAIL_SUCCESS = 'GET_MARKET_DETAIL_SUCCESS';
export const GET_MARKET_DETAIL_FAILED = 'GET_MARKET_DETAIL_FAILED';

export const GET_PRODUCT_MARKET = 'GET_PRODUCT_MARKET';
export const GET_PRODUCT_MARKET_SUCCESS = 'GET_PRODUCT_MARKET_SUCCESS';
export const GET_PRODUCT_MARKET_FAILED = 'GET_PRODUCT_MARKET_FAILED';

// SELLER
export const GET_ARTICLE = 'GET_ARTICLE';
export const GET_ARTICLE_SUCCESS = 'GET_ARTICLE_SUCCESS';
export const GET_ARTICLE_FAILED = 'GET_ARTICLE_FAILED';

export const FILTER_ARTICLE = 'FILTER_ARTICLE';

export const ADD_ARTICLE = 'ADD_ARTICLE';
export const ADD_ARTICLE_SUCCESS = 'ADD_ARTICLE_SUCCESS';
export const ADD_ARTICLE_FAILED = 'ADD_ARTICLE_FAILED';

export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL';
export const GET_ARTICLE_DETAIL_SUCCESS = 'GET_ARTICLE_DETAIL_SUCCESS';
export const GET_ARTICLE_DETAIL_FAILED = 'GET_ARTICLE_DETAIL_FAILED';

export const UPDATE_ARTICLE_DETAIL = 'UPDATE_ARTICLE_DETAIL';
export const UPDATE_ARTICLE_DETAIL_SUCCESS = 'UPDATE_ARTICLE_DETAIL_SUCCESS';
export const UPDATE_ARTICLE_DETAIL_FAILED = 'UPDATE_ARTICLE_DETAIL_FAILED';

export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAILED = 'DELETE_ARTICLE_FAILED';

/* CATEGORIES MANAGEMENT (ADMIN) */
export const GET_CATEGORIES = 'GET_CATEGORIES';
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS';
export const GET_CATEGORIES_FAILED = 'GET_CATEGORIES_FAILED';

export const ADD_CATEGORY = 'ADD_CATEGORY';
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS';
export const ADD_CATEGORY_FAILED = 'ADD_CATEGORY_FAILED';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';
export const UPDATE_CATEGORY_FAILED = 'UPDATE_CATEGORY_FAILED';

export const DELETE_CATEGORY = 'DELETE_CATEGORY';
export const DELETE_CATEGORY_SUCCESS = 'DELETE_CATEGORY_SUCCESS';
export const DELETE_CATEGORY_FAILED = 'DELETE_CATEGORY_FAILED';

/* FAQ MANAGEMENT (ADMIN) */
export const ADD_FAQ = 'ADD_FAQ';
export const ADD_FAQ_SUCCESS = 'ADD_FAQ_SUCCESS';
export const ADD_FAQ_FAILED = 'ADD_FAQ_FAILED';
export const GET_FAQ = 'GET_FAQ';
export const GET_FAQ_SUCCESS = 'GET_FAQ_SUCCESS';
export const GET_FAQ_FAILED = 'GET_FAQ_FAILED';

export const GET_FAQ_DETAIL = 'GET_FAQ_DETAIL';
export const GET_FAQ_DETAIL_SUCCESS = 'GET_FAQ_DETAIL_SUCCESS';
export const GET_FAQ_DETAIL_FAILED = 'GET_FAQ_DETAIL_FAILED';
export const UPDATE_FAQ = 'UPDATE_FAQ';
export const UPDATE_FAQ_SUCCESS = 'UPDATE_FAQ_SUCCESS';
export const UPDATE_FAQ_FAILED = 'UPDATE_FAQ_FAILED';

export const DELETE_FAQ = 'DELETE_FAQ';
export const DELETE_FAQ_SUCCESS = 'DELETE_FAQ_SUCCESS';
export const DELETE_FAQ_FAILED = 'DELETE_FAQ_FAILED';

/* WITHDRAW MANAGEMENT */
export const GET_ALL_WITHDRAW = 'GET_ALL_WITHDRAW';
export const GET_ALL_WITHDRAW_SUCCESS = 'GET_ALL_WITHDRAW_SUCCESS';
export const GET_ALL_WITHDRAW_FAILED = 'GET_ALL_WITHDRAW_FAILED';

export const ON_CHANGE_SEARCH_WITHDRAW = 'ON_CHANGE_SEARCH_WITHDRAW';
