export const BANKS = [
	{
		bank_code: 'mandiri',
		name: 'Mandiri',
		fee: 4000,
		queue: 885,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bri',
		name: 'BRI',
		fee: 4000,
		queue: 3246,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bni',
		name: 'BNI / BNI Syariah',
		fee: 4000,
		queue: 7880,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bca',
		name: 'BCA',
		fee: 4000,
		queue: 27760,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bsm',
		name: 'Bank Syariah Mandiri',
		fee: 4000,
		queue: 353,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'cimb',
		name: 'CIMB Niaga/CIMB Niaga Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'muamalat',
		name: 'Muamalat',
		fee: 4000,
		queue: 538,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'danamon',
		name: 'Danamon / Danamon Syariah',
		fee: 4000,
		queue: 11,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'permata',
		name: 'Bank Permata',
		fee: 4000,
		queue: 3841,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bii',
		name: 'Maybank Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'panin',
		name: 'Panin Bank',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'uob',
		name: 'UOB Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'ocbc',
		name: 'OCBC NISP',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'citibank',
		name: 'Citibank',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'artha',
		name: 'Bank Artha Graha Internasional',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'tokyo',
		name: 'Bank of Tokyo Mitsubishi UFJ',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'dbs',
		name: 'DBS Indonesia',
		fee: 4000,
		queue: 2061,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'standard_chartered',
		name: 'Standard Chartered Bank',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'capital',
		name: 'Bank Capital Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'anz',
		name: 'ANZ Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'boc',
		name: 'Bank of China (Hong Kong) Limited',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bumi_arta',
		name: 'Bank Bumi Arta',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'hsbc',
		name: 'HSBC Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'rabobank',
		name: 'Rabobank International Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'mayapada',
		name: 'Bank Mayapada',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bjb',
		name: 'BJB',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'dki',
		name: 'Bank DKI Jakarta',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'daerah_istimewa',
		name: 'BPD DIY',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'jawa_tengah',
		name: 'Bank Jateng',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'jawa_timur',
		name: 'Bank Jatim',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'jambi',
		name: 'Bank Jambi',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sumut',
		name: 'Bank Sumut',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sumatera_barat',
		name: 'Bank Sumbar (Bank Nagari)',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'riau_dan_kepri',
		name: 'Bank Riau Kepri',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sumsel_dan_babel',
		name: 'Bank Sumsel Babel',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'lampung',
		name: 'Bank Lampung',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'kalimantan_selatan',
		name: 'Bank Kalsel',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'kalimantan_barat',
		name: 'Bank Kalbar',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'kalimantan_timur',
		name: 'Bank Kaltim',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'kalimantan_tengah',
		name: 'Bank Kalteng',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sulselbar',
		name: 'Bank Sulselbar',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sulut',
		name: 'Bank SulutGo',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'nusa_tenggara_barat',
		name: 'Bank NTB',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bali',
		name: 'BPD Bali',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'nusa_tenggara_timur',
		name: 'Bank NTT',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'maluku',
		name: 'Bank Maluku',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'papua',
	// 	name: 'Bank Papua',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'bengkulu',
		name: 'Bank Bengkulu',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sulawesi',
		name: 'Bank Sulteng',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sulawesi_tenggara',
		name: 'Bank Sultra',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'nusantara_parahyangan',
		name: 'Bank Nusantara Parahyangan',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'india',
	// 	name: 'Bank of India Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'mestika_dharma',
		name: 'Bank Mestika Dharma',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'sinarmas',
		name: 'Bank Sinarmas',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'maspion',
		name: 'Bank Maspion Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'ganesha',
		name: 'Bank Ganesha',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'icbc',
		name: 'ICBC Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'qnb_kesawan',
		name: 'QNB Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'btn',
		name: 'BTN (Bank Tabungan Negara)',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'woori',
		name: 'Bank Woori Saudara',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'tabungan_pensiunan_nasional',
		name: 'BTPN / Jenius / BTPN Wow!',
		fee: 4000,
		queue: 136,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bri_syr',
		name: 'BRI (Bank Rakyat Indonesia) Syariah',
		fee: 4000,
		queue: 1282,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bjb_syr',
		name: 'BJB Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'mega',
		name: 'Bank Mega',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'bukopin',
		name: 'Bukopin',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'jasa_jakarta',
	// 	name: 'Bank Jasa Jakarta',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'hana',
	// 	name: 'KEB Hana Bank Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'mnc_internasional',
	// 	name: 'Bank MNC Internasional',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'agroniaga',
		name: 'BRI Agroniaga',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'sbi_indonesia',
	// 	name: 'SBI Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'royal',
	// 	name: 'Bank Royal Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'nationalnobu',
	// 	name: 'Nobu (Nationalnobu) Bank',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'mega_syr',
		name: 'Bank Mega Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'ina_perdana',
	// 	name: 'Bank Ina Perdana',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'sahabat_sampoerna',
	// 	name: 'Bank Sahabat Sampoerna',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'kesejahteraan_ekonomi',
	// 	name: 'Bank Kesejahteraan Ekonomi',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'bca_syr',
		name: 'BCA (Bank Central Asia) Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'artos',
	// 	name: 'Bank Artos Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'mayora',
	// 	name: 'Bank Mayora Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'index_selindo',
	// 	name: 'Bank Index Selindo',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'victoria_internasional',
	// 	name: 'Bank Victoria International',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'agris',
	// 	name: 'Bank Agris',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'chinatrust',
	// 	name: 'CTBC (Chinatrust) Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'commonwealth',
	// 	name: 'Commonwealth Bank',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'ccb',
		name: 'Bank China Construction Bank Indonesia',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'danamon_syr',
		name: 'Bank Danamon Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'victoria_syr',
		name: 'Bank Victoria Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'banten',
		name: 'BPD Banten',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'mutiara',
		name: 'Bank Mutiara',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'panin_syr',
		name: 'Panin Dubai Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'aceh',
		name: 'Bank Aceh',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'btpn_syr',
	// 	name: 'Bank BTPN Syariah',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'dinar',
	// 	name: 'Bank Dinar Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'harda',
	// 	name: 'Bank Harda Internasional',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'e2pay',
	// 	name: 'E2Pay',
	// 	fee: 4000,
	// 	queue: 4,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'mas',
	// 	name: 'Bank Multi Arta Sentosa (Bank MAS)',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'prima',
	// 	name: 'Bank Prima Master',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'yudha_bakti',
	// 	name: 'Bank Yudha Bakti',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'linkaja',
		name: 'LinkAja',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'dompetku',
		name: 'Dompetku',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'shinhan',
	// 	name: 'Bank Shinhan Indonesia',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'bukopin_syr',
		name: 'Bank Bukopin Syariah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	{
		bank_code: 'cnb',
		name: 'Bank CNB (Centratama Nasional Bank)',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'atmb_lsb',
	// 	name: 'ATMB LSB (BPR LSB)',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'atmb_plus',
	// 	name: 'ATMB PLUS',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	{
		bank_code: 'antardaerah',
		name: 'Bank Antardaerah',
		fee: 4000,
		queue: 209,
		status: 'OPERATIONAL',
	},
	// {
	// 	bank_code: 'mantap',
	// 	name: 'BANK MANTAP (Mandiri Taspen)',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'eka',
	// 	name: 'BPR EKA (Bank Eka)',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'doku',
	// 	name: 'DOKU',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'finnet',
	// 	name: 'FINNET',
	// 	fee: 4000,
	// 	queue: 209,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'gopay',
	// 	name: 'GoPay',
	// 	fee: 4000,
	// 	queue: 10,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'ovo',
	// 	name: 'OVO',
	// 	fee: 4000,
	// 	queue: 10,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'dana',
	// 	name: 'DANA',
	// 	fee: 4000,
	// 	queue: 10,
	// 	status: 'OPERATIONAL',
	// },
	// {
	// 	bank_code: 'shopeepay',
	// 	name: 'ShopeePay',
	// 	fee: 4000,
	// 	queue: 10,
	// 	status: 'OPERATIONAL',
	// },
];
